version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - POSTGRES_HOST=container
      - POSTGRES_PORT=5432
      - POSTGRES_DB=data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: