apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-cloud-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: i-cloud-app
  template:
    metadata:
      labels:
        app: i-cloud-app
    spec:
      containers:
      - name: i-cloud-app
        image: i-cloud-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: i-cloud-app-service
spec:
  selector:
    app: i-cloud-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer